"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import { useApiStatus } from "@/components/api-status-context";
import { SectionRule } from "@/components/section-rule";
import { StatusLabel } from "@/components/status-label";
import { ApiRequestError } from "@/lib/api/client";
import { getOpportunity } from "@/lib/api/opportunities";
import type { OpportunityDetailResponse } from "@/lib/api/types";

type RequestState = "loading" | "ready" | "not-found" | "error";
type StatusTone = "invest" | "review" | "reject";

function formatMetric(value: number) {
  return value.toFixed(2);
}

function recommendationTone(recommendation: string): StatusTone {
  const normalized = recommendation.toLowerCase();
  if (normalized === "invest" || normalized === "reject") return normalized;
  return "review";
}

function factorWidth(value: number) {
  return `${Math.min(100, Math.max(0, value))}%`;
}

function DetailRequestState({
  opportunityId,
  state,
}: {
  opportunityId: string;
  state: "not-found" | "error";
}) {
  const notFound = state === "not-found";

  return (
    <div className="page-stack detail-page">
      <Link className="back-link" href="/opportunities">← Back to opportunity set</Link>

      <header className="detail-header">
        <div>
          <span className="eyebrow">Deal analysis · Synthetic record</span>
          <h1>{notFound ? "Opportunity not found" : "API unavailable"}</h1>
          <p>{opportunityId}</p>
        </div>
      </header>

      <p className="preview-notice">
        {notFound
          ? "Request completed · No matching stored record"
          : "FastAPI connection unavailable · Detail data not loaded"}
      </p>

      <section className="terminal-panel detail-state-panel" aria-live="polite">
        <SectionRule
          title={notFound ? "No Stored Opportunity" : "Detail Service Unavailable"}
          note={notFound ? "HTTP 404" : "Connection error"}
        />
        <p className="detail-state-copy">
          {notFound
            ? `No synthetic opportunity with ID ${opportunityId} exists in the current dataset.`
            : "The opportunity detail endpoint could not be reached. The application shell remains available."}
        </p>
      </section>

      <footer className="detail-footnote">
        <span>Score semantics</span>
        <p>No model prediction is generated by this detail route.</p>
      </footer>
    </div>
  );
}

export function OpportunityDetailClient({
  opportunityId,
}: {
  opportunityId: string;
}) {
  const { setApiStatus } = useApiStatus();
  const [detail, setDetail] = useState<OpportunityDetailResponse | null>(null);
  const [requestState, setRequestState] = useState<RequestState>("loading");

  useEffect(() => {
    const controller = new AbortController();
    let active = true;

    queueMicrotask(() => {
      if (!active) return;
      setDetail(null);
      setRequestState("loading");
      setApiStatus("checking");
    });

    getOpportunity(opportunityId, controller.signal)
      .then((response) => {
        if (!active) return;
        setDetail(response);
        setRequestState("ready");
        setApiStatus("online");
      })
      .catch((error: unknown) => {
        if (!active || (error instanceof DOMException && error.name === "AbortError")) return;

        setDetail(null);
        if (error instanceof ApiRequestError && error.status === 404) {
          setRequestState("not-found");
          setApiStatus("online");
          return;
        }

        setRequestState("error");
        setApiStatus("offline");
      });

    return () => {
      active = false;
      controller.abort();
    };
  }, [opportunityId, setApiStatus]);

  if (requestState === "not-found" || requestState === "error") {
    return <DetailRequestState opportunityId={opportunityId} state={requestState} />;
  }

  const loading = requestState === "loading" || detail === null;
  const identity = detail?.identity;
  const financials = detail
    ? [
        {
          label: "Investment Size",
          value: formatMetric(detail.financials.investment_size_million),
          unit: "SAR M",
        },
        {
          label: "Expected ROI",
          value: formatMetric(detail.financials.expected_roi_percent),
          unit: "%",
        },
        {
          label: "Payback",
          value: formatMetric(detail.financials.payback_period_years),
          unit: "years",
        },
        {
          label: "Profit Margin",
          value: formatMetric(detail.financials.profit_margin_percent),
          unit: "%",
        },
      ]
    : [
        { label: "Investment Size", value: "—", unit: "SAR M" },
        { label: "Expected ROI", value: "—", unit: "%" },
        { label: "Payback", value: "—", unit: "years" },
        { label: "Profit Margin", value: "—", unit: "%" },
      ];
  const evaluation = detail?.stored_synthetic_evaluation;
  const factors = evaluation
    ? [
        { label: "Overall Risk", value: evaluation.overall_risk_score, tone: "risk" },
        { label: "Strategic Impact", value: evaluation.strategic_impact_score, tone: "positive" },
        { label: "Sustainability", value: evaluation.sustainability_score, tone: "positive" },
        { label: "Market Attractiveness", value: evaluation.market_attractiveness_score, tone: "neutral" },
        { label: "Financial Strength", value: evaluation.financial_strength_score, tone: "neutral" },
      ]
    : [
        { label: "Overall Risk", value: 0, tone: "risk" },
        { label: "Strategic Impact", value: 0, tone: "positive" },
        { label: "Sustainability", value: 0, tone: "positive" },
        { label: "Market Attractiveness", value: 0, tone: "neutral" },
        { label: "Financial Strength", value: 0, tone: "neutral" },
      ];
  const recordMetrics = [
    ["Opportunity ID", identity?.opportunity_id ?? opportunityId],
    ["Sector", identity?.sector ?? "—"],
    ["Region", identity?.region ?? "—"],
    ["Decision", evaluation?.recommendation ?? "—"],
    ["Score Source", evaluation ? "Stored dataset" : "—"],
    ["Record Type", detail ? "Synthetic" : "—"],
  ];

  return (
    <div className="page-stack detail-page" aria-busy={loading}>
      <Link className="back-link" href="/opportunities">← Back to opportunity set</Link>

      <header className="detail-header">
        <div>
          <span className="eyebrow">Deal analysis · Synthetic record</span>
          <h1>{identity?.opportunity_name ?? "Loading opportunity…"}</h1>
          <p>
            {identity?.opportunity_id ?? opportunityId}
            <span aria-hidden="true">·</span>
            {identity?.sector ?? "Loading"}
            <span aria-hidden="true">·</span>
            {identity?.region ?? "Loading"}
          </p>
        </div>
        <div className="decision-lockup">
          <span>Synthetic Opportunity Score</span>
          <strong>{evaluation ? formatMetric(evaluation.investment_score) : "—"}</strong>
          {evaluation ? (
            <StatusLabel tone={recommendationTone(evaluation.recommendation)}>
              {evaluation.recommendation}
            </StatusLabel>
          ) : (
            <StatusLabel tone="review">Checking</StatusLabel>
          )}
        </div>
      </header>

      <p className="preview-notice">
        {loading
          ? "Loading stored synthetic record from FastAPI"
          : "Live dataset record · Stored evaluation · Not a model prediction"}
      </p>

      <div className="detail-grid">
        <section className="terminal-panel detail-panel">
          <SectionRule title="Financial" note="Core opportunity economics" />
          <div className="financial-ledger">
            {financials.map((item) => (
              <div className="financial-line" key={item.label}>
                <span>{item.label}</span>
                <strong>{item.value}</strong>
                <small>{item.unit}</small>
              </div>
            ))}
          </div>
        </section>

        <section className="terminal-panel detail-panel factor-section">
          <SectionRule title="Risk & Quality" note="Stored synthetic evaluation">
            <span className="scale-key">0 <i /> 100</span>
          </SectionRule>
          <div className="factor-ledger">
            {factors.map((factor) => (
              <div className="factor-line" key={factor.label}>
                <span>{factor.label}</span>
                <div className="factor-track">
                  <i
                    className={`factor-fill factor-${factor.tone}`}
                    style={{ width: loading ? "0%" : factorWidth(factor.value) }}
                  />
                </div>
                <strong>{loading ? "—" : formatMetric(factor.value)}</strong>
              </div>
            ))}
          </div>
        </section>
      </div>

      <section className="terminal-panel raw-metrics-panel">
        <SectionRule title="Selected Opportunity Data" note="Live record identity" />
        <div className="raw-metrics-grid">
          {recordMetrics.map(([label, value]) => (
            <div key={label}><span>{label}</span><strong>{value}</strong></div>
          ))}
        </div>
      </section>

      <footer className="detail-footnote">
        <span>Score semantics</span>
        <p>
          The Synthetic Opportunity Score is the stored dataset value, not a model prediction.
          {detail ? ` ${detail.disclaimer}` : ""}
        </p>
      </footer>
    </div>
  );
}
